[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower

monitor_speed = 115200
upload_protocol = picotool

lib_deps =
    adafruit/Adafruit NeoPixel
