Import("env")
import subprocess
import os

project_dir = os.getcwd()

def get_git_info(cwd):
    try:
        commit_hash = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL, cwd=cwd
        ).decode("ascii").strip()
    except Exception:
        commit_hash = "unknown"

    try:
        commit_date = subprocess.check_output(
            ["git", "log", "-1", "--format=%cs"],
            stderr=subprocess.DEVNULL, cwd=cwd
        ).decode("ascii").strip()
    except Exception:
        commit_date = "unknown"

    return commit_hash, commit_date

commit_hash, commit_date = get_git_info(project_dir)
build_id = f"{commit_date}-{commit_hash}"

header = f"""\
#pragma once
// Auto-generated by tools/gen_version.py — do not edit
#define FW_COMMIT_HASH "{commit_hash}"
#define FW_COMMIT_DATE "{commit_date}"
#define FW_BUILD_ID   "{build_id}"
#define FW_NAME       "BondTest72"
"""

out_path = os.path.join(project_dir, "src", "build_info.h")
with open(out_path, "w") as f:
    f.write(header)

print(f"build_info.h: {build_id}")